business:
  info: Business Microservices DEV
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5168/postgres
    username: admin
    password: admin2024
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true